compile_pdf:
  stage: build
  image: registry.gitlab.com/islandoftex/images/texlive:latest
  script:
    - pdflatex old-src/main.tex
  after_script:
    - mv old-src/main.pdf tcc.pdf
  artifacts:
    paths: 
      - tcc.pdf  # instruct GitLab to keep the main.pdf file