compile_pdf:
  stage: build
  image: registry.gitlab.com/islandoftex/images/texlive:latest
  script:
    - cd "old-src"
    - pdflatex -interaction=nonstopmode main.tex
  after_script:
    - cp old-src/main.pdf tcc.pdf
  artifacts:
    paths:
      - tcc.pdf  # instruct GitLab to keep the main.pdf file
